factory.cpp: fix wrong call of abort() introduced in r22137 (I got:  factory.cpp(366) : error C2039: 'abort': Is no element of 'lyx::support')
git-svn-id: svn://svn.lyx.org/lyx/lyx-devel/trunk@22140 a592a061-630c-0410-9148-cb99ea01b6c8