Fix -Winconsistent-missing-override
Fix the following warning:

src/frontends/qt/GuiDocument.h:377:7: error: 'eventFilter' overrides a member function but is not marked 'override' [-Werror,-Winconsistent-missing-override]
        bool eventFilter(QObject * sender, QEvent * event);
             ^
/usr/include/x86_64-linux-gnu/qt5/QtCore/qobject.h:139:18: note: overridden virtual function is here
    virtual bool eventFilter(QObject *watched, QEvent *event);
                 ^

Amends 62413580dee8a4ff325da8d28419b60a95cadd71.