Fix literal string in binary context
In 1a26f9b26cff827da5, all strings in the context of regexes and
comparisons have been converted to byte-like objects for python2/3
compatibility reasons. This has not been considered in the later
commit 5c545573507bb, which makes layout2layout break with
TypeError: can't concat str to bytes.