Almost fix 'make check'. The only remaining problem is an undefined reference to lyx::utf8ToUcs4. I did not fix this since it is an interface violation that should be fixed otherwise.
git-svn-id: svn://svn.lyx.org/lyx/lyx-devel/trunk@17358 a592a061-630c-0410-9148-cb99ea01b6c8